"""
EJERCICIO 2) Para convertir entre las diferentes escalas de temperaturas Celsius (ºC), Fahrenheit 
(ºF) se realizan los siguientes cálculos: 
• De ºC a ºF: se multiplica por 1,8 y se suma 32. 
• De ºF a ºC: se resta 32 y se divide entre 1,8. 
Escribir un programa Python con dos funciones para permitir la conversión de escalas: 
convertir_celsius_fharenhait() 
convertir_fharenhait_celsius() 
2 
 
Mostrar la conversión de 53C° 
Mostrar la conversión de 77F° 
"""